Traceback (most recent call last):
  File "analyze.py", line 91, in <module>
    analyze(args.filenames)
  File "analyze.py", line 82, in analyze
    get_results(f)
  File "analyze.py", line 61, in get_results
    matrix[combo[0]-node1][combo[1]-node1]=latency_times[node_pair_index]
IndexError: list index out of range
